### ISSUE TITLE
recordedTmpを指定しても録画完了時にrecordedディレクトリにファイルが移動しない

### ISSUE THREAD

**Issue by epgdatacapbon** [l3tnun/EPGStation#377]
### 環境
* Version of EPGStation: `2.0.3`
* Version of mirakc: `0.16.1`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.10`
* OS: Debian Buster
* Architecture: Raspberry Pi 4

### Issue
...
下記の設定において録画ファイルが%ROOT%/recordedに作成されますが、録画が完了してしばらくたっても/mnt/NASディレクトリにファイルが移動しません。
```
recorded:
    - name: recorded
      path: '/mnt/NAS'
recordedTmp: '%ROOT%/recorded'
```
なお、recordedTmpの行を削除すると録画ファイルは/mnt/NASに作成されます。（正常動作）
