### ISSUE TITLE
録画済ファイルからのエンコード

### ISSUE THREAD

**Issue by narumans** [l3tnun/EPGStation#411]
### 環境
* Version of EPGStation: `2.0.8`
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.15.5`
* Version of NPM: `x.x.x`
* OS:CentOS7
* Architecture: x64

### Issue
大変ありがたいこのソフトを、いつも使わせて頂いております。
ちょとした不具合なのですが、録画済ファイルのデータからの
エンコードなのですが、エンコードをしてファイルをダウンロード
いたしますと、ファイル名がデタラメで再生出来ません。
それとそれに関する事だと思われますが、
iOS端末でダウンロードしますと、以前ではvlcアプリでダウンロード
出来ましたが、最新バージョンですとvlcアプリではstream再生しか
出来ません。以上ですが、お忙しいとは思いますが、ご回答の程
よろしくお願いします。

最後になりますが、ソフトウェア開発ご苦労様です。
V2.0.8になりまた一段と良くなりました。
ありがとうございます。
...

**Comment by stu2005** [comment]
この問題はvlc側の問題なので解決不可能だと思います。(実際僕も悩まされてます) mx playerを使えば再生できると思います。

**Comment by stu2005** [comment]
ファイル名がデタラメという問題は知りませんが、少なくともstream再生しかできない件に関してはvlcの仕様の問題なので解決不可能だと思います。mxplayer使えば再生できると思います。

**Comment by stu2005** [comment]
ファイル名がデタラメという問題に関して、状況ももう少し詳しく説明してもらえないでしょうか?

**Comment by narumans** [comment]
ファイル名が、普通でしたら番組名等詳細に表示されるのですが、エンコードしたファイルはmpegファイルでなく例えば20とかいうファイル名になるのです。ご返答から察するとこれもvlcの問題の様でもありそうですが。
お返事ありがとうございました。

**Comment by stu2005** [comment]
恐らくvlcの問題では無いと思います。私の技量不足によりお答えできるのはそれしかありません。

**Comment by l3tnun** [comment]
`config.sample.yml` の ios の URL Scheme の設定が間違っていますね。

```yaml
urlscheme:
    download:
        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL://ADDRESS
```
上記が間違いで、下記が正しいです。
ただ、FILENAME の部分が正しく動いていないですね。
修正します。

```yaml
urlscheme:
    download:
        ios: vlc-x-callback://x-callback-url/download?url=PROTOCOL://ADDRESS&filename=FILENAME
```
