### ISSUE TITLE
【要望】エンコードモード毎にエンコード数の上限を設定したい

### ISSUE THREAD

**Issue by root-sbh** [l3tnun/EPGStation#531]
### 環境
* Version of EPGStation: `2.6.11`
* OS:Ubuntu server 21.04+docker 20.10.8
* Architecture: x64

### Issue
初めまして、いつもありがたく使わせていただいています。
タイトルの通り、エンコードのモード毎に上限設定が行いたいです。
具体的には、GPUでのエンコードとCPUでのエンコード(と外部サーバーでのエンコード)を切り分けて、それぞれでエンコード数の上限設定をしたいと考えています。
```
concurrentEncodeNums:
    - tag: CPU
      Num: 1
    - tag: GPU0
      Num: 2
    - tag: EncSrv0
      Num: 2

encode:
    - name: H.264_CPU
      ～中略～
      tag: CPU
    - name: HEVC_GPU
      ～中略～
      tag: GPU0
    - name: Windows_Server
      ～中略～
      tag: EncSrv0
```
上記の様にtag別にエンコード数の上限が決められると便利かな、と思います。

改修は大変かと思うので、次善の策としては「エンコードキューへの追加直前(encodingPreCommand?)」に、エンコードモード名を環境変数で渡した上でスクリプトが実行できると似たような制御が出来そうなので、そちらもご一考いただけると幸いです。
