### ISSUE TITLE
提案：汎用的な m2ts 放送・録画 android urlscheme を使用

### ISSUE THREAD

**Issue by li-yifei** [l3tnun/EPGStation#627]
### 環境
* Version of EPGStation: `v2.6.20`
* Version of Mirakurun: `3.9.0-rc2`
* Version of Node: `v16.14`
* OS: Ubuntu 22.04, Android 13(視聴用)
* Browser: Android Chrome 107
* Architecture: x64

### Issue
Android スマホで、
**「放映中」->「外部アプリで開く」**と**「録画済み」-> Play -> TS** 
のところにプレイヤーを選べることが可能になる urlscheme です。
↓↓↓

```intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end```

↑↑↑

**デフォルト**
https://github.com/l3tnun/EPGStation/blob/19a1d8ac72b03dd77eb6236c41e8020e59ee17ca/config/config.yml.template#L44-L52

**config/config.yml の例**
```
...
urlscheme:
    m2ts:
        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL://ADDRESS
        android: intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
    video:
        ios: infuse://x-callback-url/play?url=PROTOCOL://ADDRESS
        android: intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
    download:
        ios: vlc-x-callback://x-callback-url/download?url=PROTOCOL://ADDRESS&filename=FILENAME
...
```

手元のスマホで検証した結果、 MXPlayer Pro, Kodi, nPlayer, VLC いずれも M2TS 録画/無変換ストリームを開くことができます。
P.S.: nPlayer は無変換の場合レンダリングの不具合があったようですが、変換した m2ts ストリームは OK でした。
