### ISSUE TITLE
【要望】録画先HDDを複数台登録できるようにしたい

### ISSUE THREAD

**Issue by S-K5** [l3tnun/EPGStation#688]
### 環境
* Version of EPGStation: `2.9.1`
* Version of Mirakurun: `3.9.0-rc.4`
* Version of Node: `18.15.0`
* Version of NPM: `x.x.x`
* OS: Ubuntu 22.04.4
* Architecture: x64

### Issue
一通り過去の要望一覧を見ましたが、見つかりませんでしたので投稿いたします。
EPGStationで録画HDD先を設定するところで2台以上のHDDを構成できるような機能があればいいなと思っているのですが厳しいでしょうか。
番組の管理についてですが、個人的にはHDD別に分けずに録画済みタブに全て統合されていてもいいのではと感じました。
例として、長時間録画となるスポーツの試合専用のHDDを追加したいなどの場合に役に立つのではないかと思いました。
お忙しいと思いますが、よろしくお願いします。

**Comment by tobitti0** [comment]
recordedは複数の値を持てるので、すでに複数の録画先を登録できると思いますが、そういうことではないのでしょうか？
[マニュアル](https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#%E9%8C%B2%E7%94%BB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E4%BF%9D%E5%AD%98%E5%85%88)

例
詳細予約の画面でディレクトリのプルダウンから選べるようになると思います。
```
recorded:
    - name: nasA
      path: '/mnt/nasA/recorded'  
    - name: nasB
      path: '/mnt/nasB/recorded'  
```
